obj-$(CONFIG_MYDRIVERS_HELLO_WORLD)	+= helloworld.o
obj-$(CONFIG_MYDRIVERS_MODULE_PARAM)	+= moduleparam.o
obj-$(CONFIG_MYDRIVERS_PROCFS_TEST)	+= procfs_test.o
obj-$(CONFIG_MYDRIVERS_TIMER_TEST)	+= timer_test.o
obj-$(CONFIG_MYDRIVERS_GLOBALMEM)	+= globalmem/
obj-$(CONFIG_MYDRIVERS_VMEMDISK)	+= vmemdisk/
